# Supabase Configuration
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions]
enabled = true

