services:
  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    volumes:
      - ./backend:/app
      - backend_db:/app/db
      - backend_media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py setup_local &&
        python manage.py seed_seller_profiles &&
        python manage.py seed_categories &&
        python manage.py seed_products &&
        python manage.py seed_orders &&
        python manage.py runserver 0.0.0.0:8000
      "

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  backend_db:
  backend_media:

networks:
  default:
    name: ecommerce_network


