services:
  # REACTORS - Full-Stack Web Service
  - type: web
    name: reactors
    runtime: python
    plan: free
    region: frankfurt
    branch: main
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: USE_POSTGRES
        value: True
      - key: ALLOWED_HOSTS
        value: reactors.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://reactors.onrender.com
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432

